airflow tox: Require sqlalchemy < 1.4.0
sqlalchemy 1.4.0, which comes in through airflow, was released a few hours ago.
Adjust tox.ini to disallow this new version, which fails with:

    ModuleNotFoundError: No module named 'sqlalchemy.ext.declarative.clsregistry'

Change-Id: I2e834305ba3202fd97e1736b138c2b75626be776